#!/bin/bash
#video 32 - 42:40 - 47:00
clear
echo " "
for i in {7..19}
do
	echo "$i"
done
echo " "


echo " "
for i in {7..9}
do
	if ping -c 1 -w 1 8.8.8.$i>/dev/null;
	then
		echo " Host 8.8.8.$i work ok";
	else
		echo " Host 8.8.8.$i dont work";
	fi
done
echo " "

