#!/bin/bash
#video 34 - xx:xx - XX:XX 
clear
echo " "








while [ -n "$1" ]
do
	case "$1" in
		a) echo "We have a " ;;
		b) echo "We have b " ;;
		c) echo "We have c " ;;
		*) echo "This parametr is not in list" ;;
	esac
	shift
done
echo " "
