#!/bin/bash
#video 39 -  xx:xx - xx:xx
clear
echo









exec 2>38_error.log
echo "line one - OK"
echo "Line two - OK"
exec 1>38_ok.txt
echo "Line three - OK"
echo "Line four - with error" >&2
echo
