#!/bin/bash
#video 40 -  05:40 - 11:35

trap "echo  '  We are fiks Ctrl+c'  " SIGINT
echo "Test reaction to Ctrl+c"

count=1
while [ $count -le 20 ]
do
	echo "Now coun ecual = $count"
	sleep 2
	count=$(( $count + 1 ))
done
