#!/bin/bash
#video 40 -  14:35 - 21:40

trap "echo  '  We are fiks Ctrl+c'  " SIGINT
echo "Test reaction to Ctrl+c"

count=1
while [ $count -le 10 ]
do
	echo "Now coun ecual = $count"
	sleep 2
	count=$(( $count + 1 ))
done

trap "echo  '  We change massage fron TRAP'  " SIGINT
echo "Test reaction to Ctrl+c - wersion 2"

count=1
while [ $count -le 10 ]
do
	echo "Now coun 2 ecual = $count"
	sleep 2
	count=$(( $count + 1 ))
done

