#!/bin/bash
# script 58
#video 45 -  14:55 - 20:35
echo

function myfunc {
	echo $(( $1 + $2 ))
}

if [ $# -eq  2 ]
then
	value=$(myfunc $1 $2)  
	echo "Result is $value"
else
	echo "Plese  give 2 parametrs !!!"
fi
echo
