#!/bin/bash
# script 59
#video 46 -  xxxx - xxxx
echo














function myfunc {
	echo $(( $1 + $2 ))
}

if [ $# -eq  2 ]
then
	value=$(myfunc $1 $2)  
	echo "Result is $value"
else
	echo "Plese  give 2 parametrs !!!"
fi
echo
