#!/bin/bash
# script 59
#video 46 -  02:00 - 06:00
echo

function myfunc {
	value=$(( $value + 10))
}

read -p "Please, write number: " value
myfunc
echo "Now> after function, your number was changed to : $value"

echo
