#!/bin/bash

echo -n "What is uour mane of brand?  "
read marka

case $marka in
	samsung)
	  echo "For $marka is discount 10%";;
	nokia)
	  echo "For $marka is discount 20%";;
	*)
	  echo "For $marka is discount 0%";;

esac
