#!/bin/bash
# script 64
#video 48 -  01:00 - 05:05 - 07:45 - 08:50
echo
clear
function fuctorial {
	if [ $1 -eq 1 ]
	then
		echo 1
	else
		local temp=$(( $1 - 1 ))
		local result=$(fuctorial $temp)
		echo $(( $result * $1 ))
	fi
}

read -p "Enter FACTORIAL quontity:  " value
result=$(fuctorial $value)
echo "FACTORIAL with quontity $value equal $result"
echo
