#!/bin/bash

# script 70
#video 66 -  11:25 - 17:15

clear
echo
my_path=$(echo $PATH | sed 's/:/ /g')
count=0

for directory in $my_path
do
	check=$(ls $directory)

	for item in $check
	do
		count=$[ $count + 1 ]
	done
	echo "In directory $directory - $count files"
	count=0
done
echo
