#!/bin/bash

echo "  "
echo "for example"

for n in 1 2 3;
  do
	echo  $n:
done

echo "  "
echo "for example with array"

array=(10 20 30)
for i in ${!array[@]}; do
	echo "${array[$i]}"
done

echo "  "
echo "for example from file "

for n in $(cat 8txt);
  do
	echo  $n;
done

echo  "  "
echo "for exmple - profi"
for (( i=0; i<10; i++ )); do 
	echo $i;
done


echo "   "
echo " uce while"

n=1
while [ $n -lt 4 ]
  do 
	echo $n;
	n=$(( $n+1 ));
done



echo "   "
echo " uce until"

n=10
until [ $n -lt 4 ]
  do 
	echo $n;
	n=$(( $n-1 ));
done

