#!/bin/bash
# script a06_scr
# video 05
#
clear
echo


echo -n "What is your mane of brand?  "
read marka

case $marka in
	samsung)
	  echo "For $marka is discount 10%";;
	nokia)
	  echo "For $marka is discount 20%";;
	*)
	  echo "For $marka is discount 0%";;

esac

