#!/bin/bash
# script a10_scr
# video 08
#
clear
echo
#########################################
echo "  "
echo "for example"

for n in 1 2 3;
  do
	echo  $n
done
##########################################

echo "  "
echo "for example with array"

array=(10 20 30)
for i in ${!array[@]};
do
	echo "${array[$i]}"
done

#########################################

echo "  "
echo "for example - read date from file "

for n in $(cat a10_data);
  do
	echo  $n
done
#########################################

echo  "  "
echo "for exmple - profi"
for (( i=1; i<6; i++ )); do 
	echo $i;
done
##########################################

echo "   "
echo " use while"

n=1
while [ $n -lt 4 ]
  do 
	echo $n;
	n=$(( $n+1 ));
done
##########################################


echo "   "
echo " use until"

n=1
until [ $n -eq 4 ]
  do 
	echo $n;
	n=$(( $n+1 ));
done

